// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SEGURIDAD.Infraestructura;

#nullable disable

namespace SEGURIDAD.Migrations
{
    [DbContext(typeof(SeguridadDBContext))]
    [Migration("20260903052949_AddUsuarioPermiso")]
    partial class AddUsuarioPermiso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SEGURIDAD.AccionSubModulo_.Web.Dominio.Entidad.AccionSubModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubModuloId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccionId");

                    b.HasIndex("SubModuloId");

                    b.ToTable("ACCION_SUB_MODULO", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.Accion_.Web.Dominio.Entidad.Accion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ACCION", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.Modulo_.Web.Dominio.Entidad.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MODULO", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.Permiso_.Web.Dominio.Entidad.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("PERMISO", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.Permiso_.Web.Dominio.Entidad.PermisoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_detalle_id");

                    b.Property<Guid>("AccionId")
                        .HasColumnType("uuid")
                        .HasColumnName("accion_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.Property<Guid>("SubModuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_modulo_id");

                    b.HasKey("Id");

                    b.HasIndex("AccionId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("PermisoId");

                    b.HasIndex("SubModuloId");

                    b.ToTable("PERMISO_DETALLE", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.Proveedor_.Web.Dominio.Entidad.Proveedor", b =>
                {
                    b.Property<Guid>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoUsuario")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_usuario");

                    b.Property<string>("Comentario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comentario");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Ipv4Modificacion")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("ipv4_modificacion");

                    b.Property<string>("Ipv4Registro")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("ipv4_registro");

                    b.Property<string>("Ipv6Modificacion")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("ipv6_modificacion");

                    b.Property<string>("Ipv6Registro")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("ipv6_registro");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioRegistro")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usuario_registro");

                    b.HasKey("IdProveedor");

                    b.ToTable("PROVEEDOR", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.SubModulo_.Web.Dominio.Entidad.SubModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SUB_MODULO", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.UsuarioPermiso_.Web.Dominio.Entidad.UsuarioPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_permiso_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("UsuarioId", "PermisoId")
                        .IsUnique()
                        .HasDatabaseName("UX_USUARIO_PERMISO_usuario_permiso");

                    b.ToTable("USUARIO_PERMISO", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.Usuario_.Web.Dominio.Entidad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("SEGURIDAD.AccionSubModulo_.Web.Dominio.Entidad.AccionSubModulo", b =>
                {
                    b.HasOne("SEGURIDAD.Accion_.Web.Dominio.Entidad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEGURIDAD.SubModulo_.Web.Dominio.Entidad.SubModulo", null)
                        .WithMany()
                        .HasForeignKey("SubModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SEGURIDAD.Permiso_.Web.Dominio.Entidad.PermisoDetalle", b =>
                {
                    b.HasOne("SEGURIDAD.Accion_.Web.Dominio.Entidad.Accion", "Accion")
                        .WithMany()
                        .HasForeignKey("AccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEGURIDAD.Modulo_.Web.Dominio.Entidad.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEGURIDAD.Permiso_.Web.Dominio.Entidad.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEGURIDAD.SubModulo_.Web.Dominio.Entidad.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("SubModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accion");

                    b.Navigation("Modulo");

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("SEGURIDAD.UsuarioPermiso_.Web.Dominio.Entidad.UsuarioPermiso", b =>
                {
                    b.HasOne("SEGURIDAD.Permiso_.Web.Dominio.Entidad.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEGURIDAD.Usuario_.Web.Dominio.Entidad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SEGURIDAD.Usuario_.Web.Dominio.Entidad.Usuario", b =>
                {
                    b.OwnsOne("SEGURIDAD.Usuario_.Web.Dominio.ValueObject.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("USUARIO");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
